### ISSUE TITLE
Functionality for reloading rulesets

### ISSUE THREAD

**Issue by Zero3** [giancosta86/EasyPmd#5]
Here's a feature request:

It would be nice if there was an easy way to reload rulesets. When I make a change to a ruleset, the effects are not seen before restarting Netbeans (which is quite cumbersome).

Ideally, changes to a ruleset on disk would automatically be picked up by EasyPmd (like the version control plugins), but a button somewhere in the options would be an acceptable solution too. Perhaps the "clear cache" button could be expanded to do this as well.

**Comment by giancosta86** [comment]
I have just added an "Enforce change" check box in the lower part of the Options dialog :)

**Comment by Zero3** [comment]
Great! It works! :+1: 

I think the naming and placement of the checkbox is a little confusing though. It doesn't really explain what it does, and it seems to belongs to the "Reset options" / "Verify options" buttons the way it is placed. Perhaps it would make more sense if the checkbox was a button called something like "Reload EasyPMD" instead.

**Comment by giancosta86** [comment]
The checkbox is meant to be global within the dialog, which is why it is next to the buttons. :)
Also, a change in the options might have additional side-effects - not only reloading PMD.
Finally, I'd say a "Reload" button wouldn't fit in nicely with the architecture.

For the moment being, I'd keep it as it is, sorry! ^__^

**Comment by Zero3** [comment]
No problem - just throwing in my opinion :). Thanks for the feature!
